// Copyright (c) 2025 BobLd
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading;
using System.Threading.Tasks;
using Caly.Core.Services.Interfaces;
using SharpIpp;
using SharpIpp.Models.Requests;
using SkiaSharp;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.Storage.Xps;

namespace Caly.Core.Services;

/// <summary>
/// Cross-platform print service.
/// <para>
/// On Windows, printer discovery uses the Win32 Print Spooler via CsWin32
/// (<c>EnumPrinters</c>) and jobs are submitted via the GDI printer-DC path
/// (<c>CreateDC</c> / <c>StartDoc</c> / <c>StartPage</c> / <c>StretchDIBits</c> /
/// <c>EndPage</c> / <c>EndDoc</c> / <c>DeleteDC</c>).
/// On Linux/macOS, CUPS IPP discovery is tried first with an <c>lpstat</c> fallback;
/// jobs are sent via SharpIppNext as JPEG images.
/// </para>
/// </summary>
internal sealed class PrintService : IPrintService, IDisposable
{
    // Re-used for non-Windows IPP printing only.
    private readonly SharpIppClient _ippClient = new();

    private static readonly Uri s_cupsLocalUri = new("ipp://localhost:631/");

    public void Dispose() => _ippClient.Dispose();

    // -------------------------------------------------------------------------
    // Printer discovery
    // -------------------------------------------------------------------------

    public async Task<IReadOnlyList<PrinterInfo>> GetAvailablePrintersAsync(CancellationToken token = default)
    {
        if (OperatingSystem.IsWindows())
        {
            return await GetWindowsPrintersAsync(token).ConfigureAwait(false);
        }

        try
        {
            var cupsPrinters = await GetCupsPrintersAsync(token).ConfigureAwait(false);
            if (cupsPrinters.Count > 0)
            {
                return cupsPrinters;
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"PrintService: CUPS discovery failed: {ex.Message}");
        }

        return await GetLpstatPrintersAsync(token).ConfigureAwait(false);
    }

    [SupportedOSPlatform("windows")]
    private static Task<IReadOnlyList<PrinterInfo>> GetWindowsPrintersAsync(CancellationToken token)
    {
        return Task.Run<IReadOnlyList<PrinterInfo>>(() => GetWindowsPrintersCore(token), token);
    }

    // Minimal layout for PRINTER_INFO_4W (Level 4 enumeration — fast, local-only).
    // Level 4 is explicitly recommended for printer name enumeration (MSDN).
    // PRINTER_INFO_4W is not generated by CsWin32 due to complex struct dependencies.
    [StructLayout(LayoutKind.Sequential)]
    private unsafe struct PrinterInfo4W
    {
        public char* pPrinterName;
        public char* pServerName;
        public uint  Attributes;
    }

    [SupportedOSPlatform("windows")]
    private static unsafe IReadOnlyList<PrinterInfo> GetWindowsPrintersCore(CancellationToken token)
    {
        token.ThrowIfCancellationRequested();

        var result = new List<PrinterInfo>();
        try
        {
            const uint flags = 0x00000002u | 0x00000004u; // PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS
            const uint level = 4; // PRINTER_INFO_4W — fastest for name enumeration

            // First call: get required buffer size.
            PInvoke.EnumPrinters(flags, null, level, Span<byte>.Empty, out uint needed, out _);
            if (needed == 0)
                return result;

            byte[] buffer = new byte[needed];
            if (!PInvoke.EnumPrinters(flags, null, level, buffer, out _, out uint count))
                return result;

            fixed (byte* pBuf = buffer)
            {
                var ptr = (PrinterInfo4W*)pBuf;
                for (uint i = 0; i < count; i++)
                {
                    string? name = ptr[i].pPrinterName is null ? null : new string(ptr[i].pPrinterName);
                    if (!string.IsNullOrWhiteSpace(name))
                        result.Add(new PrinterInfo(name, BuildCupsUri(name)));
                }
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"PrintService: EnumPrinters failed: {ex.Message}");
        }

        return result;
    }

    private async Task<IReadOnlyList<PrinterInfo>> GetCupsPrintersAsync(CancellationToken token)
    {
        var request = new CUPSGetPrintersRequest
        {
            OperationAttributes = new CUPSGetPrintersOperationAttributes
            {
                PrinterUri = s_cupsLocalUri
            }
        };

        var response = await _ippClient.GetCUPSPrintersAsync(request, token).ConfigureAwait(false);

        var attrs = response.PrintersAttributes;
        if (attrs is null || attrs.Length == 0)
            return [];

        var result = new List<PrinterInfo>(attrs.Length);
        foreach (var p in attrs)
        {
            var name = p.PrinterName;
            if (string.IsNullOrWhiteSpace(name))
                continue;

            var uriStr = p.PrinterUriSupported?.FirstOrDefault(u => !string.IsNullOrWhiteSpace(u));
            if (uriStr is null || !Uri.TryCreate(uriStr, UriKind.Absolute, out var uri))
                uri = BuildCupsUri(name);

            result.Add(new PrinterInfo(name, uri));
        }

        return result;
    }

    private static async Task<IReadOnlyList<PrinterInfo>> GetLpstatPrintersAsync(CancellationToken token)
    {
        var output = await RunProcessAsync("lpstat", ["-a"], token).ConfigureAwait(false);

        var result = new List<PrinterInfo>();
        foreach (var line in output.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var space = line.IndexOf(' ');
            var name = space > 0 ? line[..space] : line;
            if (!string.IsNullOrWhiteSpace(name))
                result.Add(new PrinterInfo(name, BuildCupsUri(name)));
        }

        return result;
    }

    private static Uri BuildCupsUri(string printerName)
        => new($"ipp://localhost:631/printers/{Uri.EscapeDataString(printerName)}");

    // -------------------------------------------------------------------------
    // Printing
    // -------------------------------------------------------------------------

    public async Task PrintDocumentAsync(
        PrinterInfo printer,
        IPdfDocumentService documentService,
        IReadOnlyList<PrintPageInfo> pages,
        CancellationToken token = default)
    {
        // Render all pages to bitmaps first (async, independent of delivery path).
        var bitmaps = new SKBitmap?[pages.Count];
        try
        {
            for (int i = 0; i < pages.Count; i++)
            {
                token.ThrowIfCancellationRequested();
                bitmaps[i] = await RenderPageToBitmapAsync(documentService, pages[i], token)
                    .ConfigureAwait(false);
            }

            if (OperatingSystem.IsWindows())
                await PrintWindowsAsync(printer, documentService.FileName, bitmaps, token).ConfigureAwait(false);
            else
                await PrintIppAsync(printer, documentService.FileName, bitmaps, token).ConfigureAwait(false);
        }
        finally
        {
            foreach (var bmp in bitmaps)
                bmp?.Dispose();
        }
    }

    // -------------------------------------------------------------------------
    // Windows — GDI printer-DC path
    // -------------------------------------------------------------------------

    /// <summary>
    /// Prints pre-rendered page bitmaps via the GDI printer Device Context.
    /// All Win32 GDI calls are made on a single threadpool thread to avoid
    /// handle affinity issues.
    /// </summary>
    [SupportedOSPlatform("windows")]
    private static Task PrintWindowsAsync(
        PrinterInfo printer,
        string? documentName,
        SKBitmap?[] bitmaps,
        CancellationToken token)
    {
        return Task.Run(() => PrintWindowsCore(printer, documentName, bitmaps, token), token);
    }

    [SupportedOSPlatform("windows")]
    private static unsafe void PrintWindowsCore(
        PrinterInfo printer,
        string? documentName,
        SKBitmap?[] bitmaps,
        CancellationToken token)
    {
        // CreateDCW has a friendly string overload generated by CsWin32.
        HDC hdc = PInvoke.CreateDCW(null, printer.Name, null, null);
        if (hdc.IsNull)
        {
            throw new InvalidOperationException(
                $"Cannot create DC for printer '{printer.Name}' (Win32 error {Marshal.GetLastWin32Error()}).");
        }

        try
        {
            // StartDoc copies the document name immediately; fix the string for the duration of the call.
            int startDocResult;
            fixed (char* docNamePtr = documentName ?? "Document")
            {
                DOCINFOW docInfo;
                docInfo.cbSize = sizeof(DOCINFOW);
                docInfo.lpszDocName = docNamePtr;
                docInfo.lpszOutput = default;
                docInfo.lpszDatatype = default;
                docInfo.fwType = 0;
                startDocResult = PInvoke.StartDoc(hdc, in docInfo);
            }

            if (startDocResult <= 0)
            {
                throw new InvalidOperationException(
                    $"StartDoc failed (Win32 error {Marshal.GetLastWin32Error()}).");
            }

            try
            {
                int printerW = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.HORZRES);
                int printerH = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.VERTRES);

                foreach (var bitmap in bitmaps)
                {
                    token.ThrowIfCancellationRequested();

                    if (PInvoke.StartPage(hdc) <= 0)
                    {
                        throw new InvalidOperationException(
                            $"StartPage failed (Win32 error {Marshal.GetLastWin32Error()}).");
                    }

                    try
                    {
                        if (bitmap is not null)
                        {
                            DrawBitmapToHdc(hdc, bitmap, printerW, printerH);
                        }
                    }
                    finally
                    {
                        _ = PInvoke.EndPage(hdc);
                    }
                }
            }
            finally
            {
                _ = PInvoke.EndDoc(hdc);
            }
        }
        finally
        {
            _ = PInvoke.DeleteDC(hdc);
        }
    }

    /// <summary>
    /// Blits <paramref name="bitmap"/> onto the printer DC using <c>StretchDIBits</c>,
    /// scaling to fill the entire printable area while preserving aspect ratio.
    /// </summary>
    [SupportedOSPlatform("windows")]
    private static unsafe void DrawBitmapToHdc(HDC hdc, SKBitmap bitmap, int printerW, int printerH)
    {
        // Compute destination rect preserving aspect ratio.
        float bitmapAspect = (float)bitmap.Width / bitmap.Height;
        float printerAspect = (float)printerW / printerH;

        int destW, destH, destX, destY;
        if (bitmapAspect >= printerAspect)
        {
            destW = printerW;
            destH = (int)(printerW / bitmapAspect);
            destX = 0;
            destY = (printerH - destH) / 2;
        }
        else
        {
            destH = printerH;
            destW = (int)(printerH * bitmapAspect);
            destX = (printerW - destW) / 2;
            destY = 0;
        }

        // SKBitmap with BGRA8888 matches the Windows DIB RGBQUAD memory layout.
        // Negative biHeight signals a top-down bitmap (matching SkiaSharp's origin).
        BITMAPINFO bmi = default;
        bmi.bmiHeader.biSize = (uint)sizeof(BITMAPINFOHEADER);
        bmi.bmiHeader.biWidth = bitmap.Width;
        bmi.bmiHeader.biHeight = -bitmap.Height;
        bmi.bmiHeader.biPlanes = 1;
        bmi.bmiHeader.biBitCount = 32;
        bmi.bmiHeader.biCompression = 0; // BI_RGB

        _ = PInvoke.StretchDIBits(hdc,
            destX, destY, destW, destH,
            0, 0, bitmap.Width, bitmap.Height,
            (void*)bitmap.GetPixels(),
            &bmi,
            DIB_USAGE.DIB_RGB_COLORS,
            ROP_CODE.SRCCOPY);
    }

    // -------------------------------------------------------------------------
    // Non-Windows — IPP path (JPEG images)
    // -------------------------------------------------------------------------

    private async Task PrintIppAsync(
        PrinterInfo printer,
        string? documentName,
        SKBitmap?[] bitmaps,
        CancellationToken token)
    {
        string docName = documentName ?? "Document";

        // Send each page as a JPEG image/jpeg IPP document.
        // Use PrintJob for the first page and SendDocument for subsequent pages
        // so that all pages land in a single print queue entry.
        int? jobId = null;

        for (int i = 0; i < bitmaps.Length; i++)
        {
            token.ThrowIfCancellationRequested();

            var bitmap = bitmaps[i];
            if (bitmap is null)
            {
                continue;
            }

            bool isLast = i == bitmaps.Length - 1
                          || Array.TrueForAll(bitmaps[(i + 1)..], b => b is null);

            using var jpegStream = EncodeJpeg(bitmap);

            if (jobId is null)
            {
                // First (or only) page — create the print job.
                var printRequest = new PrintJobRequest
                {
                    Document = jpegStream,
                    OperationAttributes = new PrintJobOperationAttributes
                    {
                        PrinterUri = printer.IppUri,
                        DocumentFormat = "image/jpeg",
                        DocumentName = docName
                    }
                };

                var printResponse = await _ippClient.PrintJobAsync(printRequest, token)
                    .ConfigureAwait(false);

                if ((short)printResponse.StatusCode >= 0x0100)
                {
                    throw new InvalidOperationException($"The printer rejected the job (IPP status {printResponse.StatusCode:X4}: {printResponse.StatusCode}).");
                }

                if (!isLast)
                {
                    jobId = printResponse.JobAttributes?.JobId;
                }
            }
            else
            {
                // Subsequent pages — append to the existing job via Send-Document.
                var sendRequest = new SendDocumentRequest
                {
                    Document = jpegStream,
                    OperationAttributes = new SendDocumentOperationAttributes
                    {
                        PrinterUri = printer.IppUri,
                        JobId = jobId.Value,
                        DocumentFormat = "image/jpeg",
                        LastDocument = isLast
                    }
                };

                var sendResponse = await _ippClient.SendDocumentAsync(sendRequest, token).ConfigureAwait(false);

                if ((short)sendResponse.StatusCode >= 0x0100)
                {
                    throw new InvalidOperationException($"Send-Document failed (IPP status {sendResponse.StatusCode:X4}: {sendResponse.StatusCode}).");
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // Rendering — SKPicture → SKBitmap
    // -------------------------------------------------------------------------

    private static async Task<SKBitmap?> RenderPageToBitmapAsync(
        IPdfDocumentService documentService,
        PrintPageInfo pageInfo,
        CancellationToken token)
    {
        var pageSize = await documentService.GetPageSizeAsync(pageInfo.PageNumber, token)
            .ConfigureAwait(false);
        if (pageSize is null)
        {
            return null;
        }

        using var picRef = await documentService.GetRenderPageAsync(pageInfo.PageNumber, token)
            .ConfigureAwait(false);
        if (picRef is null)
        {
            return null;
        }

        float ppiScale = (float)documentService.PpiScale;
        float pdfW = (float)pageSize.Value.Width;
        float pdfH = (float)pageSize.Value.Height;
        int rotation = pageInfo.Rotation;

        // Bitmap dimensions at PpiScale resolution, with rotation taken into account.
        int bitmapW = (rotation == 90 || rotation == 270)
            ? (int)(pdfH * ppiScale)
            : (int)(pdfW * ppiScale);
        int bitmapH = (rotation == 90 || rotation == 270)
            ? (int)(pdfW * ppiScale)
            : (int)(pdfH * ppiScale);

        // SKBitmap is created on the caller's thread; the canvas draw is synchronous.
        var bitmap = new SKBitmap(bitmapW, bitmapH, SKColorType.Bgra8888, SKAlphaType.Premul);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(SKColors.White);

        // Apply the same rotation transform used for on-screen rendering.
        // The SKPicture coordinate space is ppiScale × PDF-point units.
        switch (rotation)
        {
            case 90:
                canvas.Translate(bitmapW, 0);
                canvas.RotateDegrees(90);
                break;
            case 180:
                canvas.Translate(bitmapW, bitmapH);
                canvas.RotateDegrees(180);
                break;
            case 270:
                canvas.Translate(0, bitmapH);
                canvas.RotateDegrees(270);
                break;
        }

        canvas.DrawPicture(picRef.Item);
        canvas.Flush();

        return bitmap;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static MemoryStream EncodeJpeg(SKBitmap bitmap)
    {
        var stream = new MemoryStream();
        using var data = bitmap.Encode(SKEncodedImageFormat.Jpeg, quality: 100);
        data.SaveTo(stream);
        stream.Position = 0;
        return stream;
    }

    private static async Task<string> RunProcessAsync(string command, string[] args, CancellationToken token)
    {
        var psi = new System.Diagnostics.ProcessStartInfo(command)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        foreach (var arg in args)
        {
            psi.ArgumentList.Add(arg);
        }

        using var process = System.Diagnostics.Process.Start(psi);
        if (process is null)
        {
            return string.Empty;
        }

        var output = await process.StandardOutput.ReadToEndAsync(token).ConfigureAwait(false);
        await process.WaitForExitAsync(token).ConfigureAwait(false);
        return output;
    }
}
